import { Result } from '@/src/result';
import { ResultAsync } from '../../src';

describe('Result', () => {
  describe('compensateAsync', () => {
    describe('Promise', () => {
      test('takes the result from the second result, when previous result fails', async () => {
        const sut = Result.failure('ðŸ’¥');

        const innerResult = await sut
          .compensateAsync(() => Promise.resolve(Result.success('âœ…')))
          .toPromise();

        return expect(innerResult).toSucceedWith('âœ…');
      });

      test('takes the result from the first result, when it succeeds', async () => {
        const sut = Result.success('âœ…');

        const innerResult = await sut
          .compensateAsync(() => Promise.resolve(Result.failure('ðŸ’¥')))
          .toPromise();

        return expect(innerResult).toSucceedWith('âœ…');
      });

      test('takes the failure from the second result, when both fail', async () => {
        const sut = Result.failure('ðŸ’¥');

        const innerResult = await sut
          .compensateAsync(() => Promise.resolve(Result.failure('ðŸ’¥ðŸ’¥')))
          .toPromise();

        return expect(innerResult).toFailWith('ðŸ’¥ðŸ’¥');
      });
    });

    describe('ResultAsync', () => {
      test('takes the result from the second result, when previous result fails', async () => {
        const sut = Result.failure('ðŸ’¥');

        const innerResult = await sut
          .compensateAsync(() => ResultAsync.success('âœ…'))
          .toPromise();

        return expect(innerResult).toSucceedWith('âœ…');
      });

      test('takes the result from the first result, when it succeeds', async () => {
        const sut = Result.success('âœ…');

        const innerResult = await sut
          .compensateAsync(() => ResultAsync.failure('ðŸ’¥'))
          .toPromise();

        return expect(innerResult).toSucceedWith('âœ…');
      });

      test('takes the failure from the second result, when both fail', async () => {
        const sut = Result.failure('ðŸ’¥');

        const innerResult = await sut
          .compensateAsync(() => ResultAsync.failure('ðŸ’¥ðŸ’¥'))
          .toPromise();

        return expect(innerResult).toFailWith('ðŸ’¥ðŸ’¥');
      });
    });

    test('calls projection with first result error', async () => {
      const sut = Result.failure('ðŸ’¥');
      const projection = vi.fn(() => ResultAsync.success('âœ…'));

      await sut.compensateAsync(projection).toPromise();

      expect(projection).toBeCalledWith('ðŸ’¥');
    });
  });
});
