import { ResultAsync } from '@/src/resultAsync';

describe('ResultAsync', () => {
  describe('combine', () => {
    it('succeeds with one successful ResultAsync', async () => {
      const success = ResultAsync.success('âœ…');

      const result = ResultAsync.combine({ success });

      await expect(result.getValueOrThrow()).resolves.toEqual({
        success: 'âœ…',
      });
    });

    it('succeeds with one successful ResultAsync', async () => {
      const result = ResultAsync.combine({
        first: ResultAsync.success('âœ…'),
        second: ResultAsync.success('âœ…'),
      });

      await expect(result.getValueOrThrow()).resolves.toEqual({
        first: 'âœ…',
        second: 'âœ…',
      });
    });

    it('fails with one failed ResultAsync', async () => {
      const failure = ResultAsync.failure('ðŸ’¥');

      const result = ResultAsync.combine({ failure });

      await expect(result.isFailure).resolves.toEqual(true);
    });

    it('fails with one successful and one failed ResultAsync', async () => {
      const result = ResultAsync.combine({
        success: ResultAsync.success('âœ…'),
        failure: ResultAsync.failure('ðŸ’¥'),
      });

      await expect(result.isFailure).resolves.toEqual(true);
      await expect(result.getErrorOrThrow()).resolves.toEqual(
        'Failure in "failure": ðŸ’¥'
      );
    });
  });

  it('succeeds with one successful Promise', async () => {
    const success = Promise.resolve('âœ…');

    const result = ResultAsync.combine({ success });

    await expect(result.getValueOrThrow()).resolves.toEqual({
      success: 'âœ…',
    });
  });

  it('succeeds with one successful Promises', async () => {
    const result = ResultAsync.combine({
      first: Promise.resolve('âœ…'),
      second: Promise.resolve('âœ…'),
    });

    await expect(result.getValueOrThrow()).resolves.toEqual({
      first: 'âœ…',
      second: 'âœ…',
    });
  });

  it('fails with one successful and one failed Promise', async () => {
    const result = ResultAsync.combine({
      success: Promise.resolve('âœ…'),
      failure: Promise.reject('ðŸ’¥'),
    });

    await expect(result.isFailure).resolves.toEqual(true);
    await expect(result.getErrorOrThrow()).resolves.toEqual(
      'Failure in "failure": Unknown error'
    );
  });

  it('fails with one successful and one failed Promise', async () => {
    const result = ResultAsync.combine({
      success: Promise.resolve('âœ…'),
      failure: Promise.reject(new Error('ðŸ’¥')),
    });

    await expect(result.isFailure).resolves.toEqual(true);
    await expect(result.getErrorOrThrow()).resolves.toEqual(
      'Failure in "failure": ðŸ’¥'
    );
  });

  it('fails with one successful Promise and one failed Result', async () => {
    const result = ResultAsync.combine({
      success: Promise.resolve('âœ…'),
      failure: ResultAsync.failure('ðŸ’¥'),
    });

    await expect(result.isFailure).resolves.toEqual(true);
    await expect(result.getErrorOrThrow()).resolves.toEqual(
      'Failure in "failure": ðŸ’¥'
    );
  });
});
